'use client';

import { useState } from 'react';
import { ChevronDown, ChevronUp, Clipboard, ClipboardCheck, Bookmark, BookmarkCheck, Share2 } from 'lucide-react';
import { cn } from '@/lib/utils';
import { TicketLeg } from './TicketLeg';
import type { Ticket, TicketTierKey } from '@/types';

// ── Tier style map — one signal colour per risk band, nothing decorative ─────

const TIER_STYLES: Record<TicketTierKey, {
  border:   string;   // left edge accent
  bgSubtle: string;
  text:     string;
  badgeBg:  string;
  legColor: string;
  legBg:    string;
  probBar:  string;
}> = {
  ultra_safe: {
    border:   'border-l-up',
    bgSubtle: 'bg-up/[0.04]',
    text:     'text-up',
    badgeBg:  'bg-up/10 text-up',
    legColor: 'text-up',
    legBg:    'bg-up/10',
    probBar:  'bg-up',
  },
  safe: {
    border:   'border-l-foreground/40',
    bgSubtle: 'bg-muted/30',
    text:     'text-foreground',
    badgeBg:  'bg-muted text-foreground',
    legColor: 'text-foreground',
    legBg:    'bg-muted',
    probBar:  'bg-foreground/60',
  },
  moderate: {
    border:   'border-l-hold',
    bgSubtle: 'bg-hold/[0.04]',
    text:     'text-hold',
    badgeBg:  'bg-hold/10 text-hold',
    legColor: 'text-hold',
    legBg:    'bg-hold/10',
    probBar:  'bg-hold',
  },
  risky: {
    border:   'border-l-down',
    bgSubtle: 'bg-down/[0.04]',
    text:     'text-down',
    badgeBg:  'bg-down/10 text-down',
    legColor: 'text-down',
    legBg:    'bg-down/10',
    probBar:  'bg-down',
  },
};

const CONFIDENCE_STYLES = {
  high:   'bg-up/10 text-up',
  medium: 'bg-hold/10 text-hold',
  low:    'bg-down/10 text-down',
};

// ── Props ─────────────────────────────────────────────────────────────────────

interface TicketCardProps {
  ticket:    Ticket;
  isSaved?:  boolean;
  onSave?:   (id: string) => void;
  defaultExpanded?: boolean;
}

// ── Component ─────────────────────────────────────────────────────────────────

export function TicketCard({ ticket, isSaved = false, onSave, defaultExpanded = false }: TicketCardProps) {
  const [expanded, setExpanded] = useState(defaultExpanded);
  const [copied,   setCopied]   = useState(false);

  const s = TIER_STYLES[ticket.tier] ?? TIER_STYLES.safe;
  const combinedPct = Math.round(ticket.combined_probability * 100);
  const generatedTime = new Date(ticket.generated_at).toLocaleTimeString([], {
    hour: '2-digit', minute: '2-digit',
  });

  async function handleCopy() {
    const lines = [
      `${ticket.emoji} ${ticket.name} Ticket — ${ticket.combined_odds}x`,
      '',
      ...ticket.legs.map(
        (l, i) => `${i + 1}. ${l.match} → ${l.selection} @ ${l.odds} (${Math.round(l.probability * 100)}%)`
      ),
      '',
      `Combined Probability: ${combinedPct}%`,
      `Potential Return: $${ticket.potential_return_per_unit} per $1 staked`,
      'Generated by BetAction AI',
    ].join('\n');

    try {
      await navigator.clipboard.writeText(lines);
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    } catch {
      // clipboard unavailable — silent fail
    }
  }

  async function handleShare() {
    const text = `Check out this ${ticket.name} betting ticket with ${ticket.legs.length} legs and ${ticket.combined_odds}x odds! — BetAction AI`;
    if (navigator.share) {
      await navigator.share({ title: 'BetAction Ticket', text }).catch(() => {});
    } else {
      await handleCopy();
    }
  }

  return (
    <div className={cn(
      'rounded-lg border border-border border-l-2 overflow-hidden',
      'transition-colors duration-150',
      s.border, s.bgSubtle,
    )}>

      {/* ── Header (always visible) ── */}
      <button
        onClick={() => setExpanded((v) => !v)}
        className="w-full text-left px-4 pt-3 pb-2.5 flex items-start justify-between gap-3"
      >
        <div className="flex items-center gap-2.5 flex-1 min-w-0">
          {/* Tier badge */}
          <span className={cn('tick shrink-0', s.badgeBg)}>
            {ticket.name}
          </span>
          {/* Confidence */}
          <span className={cn('tick shrink-0', CONFIDENCE_STYLES[ticket.confidence])}>
            {ticket.confidence}
          </span>
          {/* Leg count */}
          <span className="label shrink-0">
            {ticket.legs.length} leg{ticket.legs.length !== 1 ? 's' : ''}
          </span>
        </div>

        <div className="flex items-center gap-3 shrink-0">
          {/* Combined odds */}
          <div className="text-right">
            <div className={cn('num text-xl font-semibold', s.text)}>
              {ticket.combined_odds}x
            </div>
            <div className="label">combined odds</div>
          </div>
          {/* Expand chevron */}
          <div className="text-muted-foreground">
            {expanded ? <ChevronUp className="h-4 w-4" /> : <ChevronDown className="h-4 w-4" />}
          </div>
        </div>
      </button>

      {/* ── Collapsed preview (top 2 legs) ── */}
      {!expanded && (
        <div className="px-4 pb-3 space-y-1">
          {ticket.legs.slice(0, 2).map((leg) => (
            <div key={leg.fixture_id} className="flex items-center gap-2 text-xs text-muted-foreground">
              <span className="w-1 h-1 rounded-sm bg-muted-foreground/50 shrink-0" />
              <span className="truncate">{leg.match}</span>
              <span className={cn('shrink-0 font-medium', s.text)}>{leg.selection}</span>
            </div>
          ))}
          {ticket.legs.length > 2 && (
            <p className="text-xs text-muted-foreground pl-3">
              +{ticket.legs.length - 2} more
            </p>
          )}
        </div>
      )}

      {/* ── Expanded legs list ── */}
      {expanded && (
        <div className="px-4 border-t border-border">
          {ticket.legs.map((leg, i) => (
            <div key={leg.fixture_id}>
              <TicketLeg
                leg={leg}
                index={i}
                tierColor={s.legColor}
                tierBg={s.legBg}
              />
              {i < ticket.legs.length - 1 && (
                <div className="border-t border-border/50" />
              )}
            </div>
          ))}
        </div>
      )}

      {/* ── Footer ── */}
      <div className={cn('px-4 py-3 border-t border-border space-y-3', expanded && 'bg-muted/20')}>
        {/* Combined probability bar */}
        <div className="space-y-1">
          <div className="flex items-center justify-between">
            <span className="label">Combined probability</span>
            <span className={cn('num text-xs font-semibold', s.text)}>{combinedPct}%</span>
          </div>
          <div className="stat-bar">
            <div
              className={cn('h-full', s.probBar)}
              style={{ width: `${Math.min(combinedPct, 100)}%` }}
            />
          </div>
        </div>

        {/* Return + actions row */}
        <div className="flex items-center justify-between gap-2 flex-wrap">
          <p className="text-xs text-muted-foreground">
            Return <span className={cn('num font-semibold', s.text)}>${ticket.potential_return_per_unit}</span>
            <span className="text-muted-foreground/60"> / $1 staked</span>
          </p>

          <div className="flex items-center gap-1.5">
            {/* Copy */}
            <button
              onClick={handleCopy}
              title="Copy ticket"
              className={cn(
                'flex items-center gap-1 text-xs px-2 py-1 rounded-sm border transition-colors duration-150',
                copied
                  ? 'border-primary/50 bg-primary/10 text-primary'
                  : 'border-border hover:border-muted-foreground/40 bg-muted/30 hover:bg-muted/60 text-muted-foreground hover:text-foreground'
              )}
            >
              {copied
                ? <><ClipboardCheck className="h-3 w-3" /> Copied</>
                : <><Clipboard className="h-3 w-3" /> Copy</>
              }
            </button>

            {/* Save */}
            {onSave && (
              <button
                onClick={() => onSave(ticket.id)}
                title={isSaved ? 'Unsave ticket' : 'Save ticket'}
                className={cn(
                  'flex items-center gap-1 text-xs px-2 py-1 rounded-sm border transition-colors duration-150',
                  isSaved
                    ? cn(s.badgeBg, 'border-current')
                    : 'border-border hover:border-muted-foreground/40 bg-muted/30 hover:bg-muted/60 text-muted-foreground hover:text-foreground'
                )}
              >
                {isSaved
                  ? <><BookmarkCheck className="h-3 w-3" /> Saved</>
                  : <><Bookmark className="h-3 w-3" /> Save</>
                }
              </button>
            )}

            {/* Share */}
            <button
              onClick={handleShare}
              title="Share ticket"
              className="flex items-center gap-1 text-xs px-2 py-1 rounded-sm border border-border hover:border-muted-foreground/40 bg-muted/30 hover:bg-muted/60 text-muted-foreground hover:text-foreground transition-colors duration-150"
            >
              <Share2 className="h-3 w-3" /> Share
            </button>
          </div>
        </div>

        <p className="label">Generated {generatedTime}</p>
      </div>
    </div>
  );
}
