'use client';

import { useState } from 'react';
import { ChevronDown, ChevronUp, Clipboard, ClipboardCheck, Bookmark, BookmarkCheck, Share2 } from 'lucide-react';
import { cn } from '@/lib/utils';
import { TicketLeg } from './TicketLeg';
import type { Ticket, TicketTierKey } from '@/types';

// ── Tier style map ────────────────────────────────────────────────────────────

const TIER_STYLES: Record<TicketTierKey, {
  border:     string;
  glow:       string;
  bgSubtle:   string;
  text:       string;
  badgeBg:    string;
  legColor:   string;
  legBg:      string;
  probBar:    string;
}> = {
  ultra_safe: {
    border:   'border-l-emerald-500',
    glow:     'hover:shadow-emerald-500/20',
    bgSubtle: 'bg-emerald-500/5',
    text:     'text-emerald-400',
    badgeBg:  'bg-emerald-500/15 text-emerald-400',
    legColor: 'text-emerald-400',
    legBg:    'bg-emerald-500/15',
    probBar:  'bg-emerald-500',
  },
  safe: {
    border:   'border-l-blue-500',
    glow:     'hover:shadow-blue-500/20',
    bgSubtle: 'bg-blue-500/5',
    text:     'text-blue-400',
    badgeBg:  'bg-blue-500/15 text-blue-400',
    legColor: 'text-blue-400',
    legBg:    'bg-blue-500/15',
    probBar:  'bg-blue-500',
  },
  moderate: {
    border:   'border-l-amber-500',
    glow:     'hover:shadow-amber-500/20',
    bgSubtle: 'bg-amber-500/5',
    text:     'text-amber-400',
    badgeBg:  'bg-amber-500/15 text-amber-400',
    legColor: 'text-amber-400',
    legBg:    'bg-amber-500/15',
    probBar:  'bg-amber-500',
  },
  risky: {
    border:   'border-l-red-500',
    glow:     'hover:shadow-red-500/20',
    bgSubtle: 'bg-red-500/5',
    text:     'text-red-400',
    badgeBg:  'bg-red-500/15 text-red-400',
    legColor: 'text-red-400',
    legBg:    'bg-red-500/15',
    probBar:  'bg-red-500',
  },
};

const CONFIDENCE_STYLES = {
  high:   'bg-emerald-500/15 text-emerald-400',
  medium: 'bg-amber-500/15 text-amber-400',
  low:    'bg-red-500/15 text-red-400',
};

// ── Props ─────────────────────────────────────────────────────────────────────

interface TicketCardProps {
  ticket:    Ticket;
  isSaved?:  boolean;
  onSave?:   (id: string) => void;
  defaultExpanded?: boolean;
}

// ── Component ─────────────────────────────────────────────────────────────────

export function TicketCard({ ticket, isSaved = false, onSave, defaultExpanded = false }: TicketCardProps) {
  const [expanded, setExpanded] = useState(defaultExpanded);
  const [copied,   setCopied]   = useState(false);

  const s = TIER_STYLES[ticket.tier] ?? TIER_STYLES.safe;
  const combinedPct = Math.round(ticket.combined_probability * 100);
  const generatedTime = new Date(ticket.generated_at).toLocaleTimeString([], {
    hour: '2-digit', minute: '2-digit',
  });

  async function handleCopy() {
    const lines = [
      `${ticket.emoji} ${ticket.name} Ticket — ${ticket.combined_odds}x`,
      '',
      ...ticket.legs.map(
        (l, i) => `${i + 1}. ${l.match} → ${l.selection} @ ${l.odds} (${Math.round(l.probability * 100)}%)`
      ),
      '',
      `Combined Probability: ${combinedPct}%`,
      `Potential Return: $${ticket.potential_return_per_unit} per $1 staked`,
      'Generated by BetAction AI',
    ].join('\n');

    try {
      await navigator.clipboard.writeText(lines);
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    } catch {
      // clipboard unavailable — silent fail
    }
  }

  async function handleShare() {
    const text = `Check out this ${ticket.name} betting ticket with ${ticket.legs.length} legs and ${ticket.combined_odds}x odds! — BetAction AI`;
    if (navigator.share) {
      await navigator.share({ title: 'BetAction Ticket', text }).catch(() => {});
    } else {
      await handleCopy();
    }
  }

  return (
    <div className={cn(
      'rounded-xl border border-border/60 border-l-4 overflow-hidden',
      'transition-all duration-200 hover:shadow-lg hover:shadow-black/30',
      s.border, s.glow, s.bgSubtle,
    )}>

      {/* ── Header (always visible) ── */}
      <button
        onClick={() => setExpanded((v) => !v)}
        className="w-full text-left px-5 pt-4 pb-3 flex items-start justify-between gap-3"
      >
        <div className="flex items-center gap-3 flex-1 min-w-0">
          {/* Tier badge */}
          <span className={cn('flex items-center gap-1.5 text-xs font-semibold px-2.5 py-1 rounded-full shrink-0', s.badgeBg)}>
            {ticket.emoji} {ticket.name}
          </span>
          {/* Confidence */}
          <span className={cn('text-xs px-2 py-0.5 rounded-full font-medium shrink-0', CONFIDENCE_STYLES[ticket.confidence])}>
            {ticket.confidence}
          </span>
          {/* Leg count */}
          <span className="text-xs text-muted-foreground shrink-0">
            {ticket.legs.length} leg{ticket.legs.length !== 1 ? 's' : ''}
          </span>
        </div>

        <div className="flex items-center gap-3 shrink-0">
          {/* Combined odds */}
          <div className="text-right">
            <div className={cn('text-2xl font-black tabular-nums', s.text)}>
              {ticket.combined_odds}x
            </div>
            <div className="text-[10px] text-muted-foreground">combined odds</div>
          </div>
          {/* Expand chevron */}
          <div className="text-muted-foreground">
            {expanded ? <ChevronUp className="h-4 w-4" /> : <ChevronDown className="h-4 w-4" />}
          </div>
        </div>
      </button>

      {/* ── Collapsed preview (top 2 legs) ── */}
      {!expanded && (
        <div className="px-5 pb-3 space-y-1">
          {ticket.legs.slice(0, 2).map((leg) => (
            <div key={leg.fixture_id} className="flex items-center gap-2 text-xs text-muted-foreground">
              <span className="w-1.5 h-1.5 rounded-full bg-muted-foreground/50 shrink-0" />
              <span className="truncate">{leg.match}</span>
              <span className={cn('shrink-0 font-medium', s.text)}>{leg.selection}</span>
            </div>
          ))}
          {ticket.legs.length > 2 && (
            <p className="text-xs text-muted-foreground pl-3.5">
              +{ticket.legs.length - 2} more…
            </p>
          )}
        </div>
      )}

      {/* ── Expanded legs list ── */}
      {expanded && (
        <div className="px-5 border-t border-border/40">
          {ticket.legs.map((leg, i) => (
            <div key={leg.fixture_id}>
              <TicketLeg
                leg={leg}
                index={i}
                tierColor={s.legColor}
                tierBg={s.legBg}
              />
              {i < ticket.legs.length - 1 && (
                <div className="border-t border-border/30" />
              )}
            </div>
          ))}
        </div>
      )}

      {/* ── Footer ── */}
      <div className={cn('px-5 py-3 border-t border-border/40 space-y-3', expanded && 'bg-card/30')}>
        {/* Combined probability bar */}
        <div className="space-y-1">
          <div className="flex items-center justify-between text-xs">
            <span className="text-muted-foreground">Combined Probability</span>
            <span className={cn('font-semibold tabular-nums', s.text)}>{combinedPct}%</span>
          </div>
          <div className="h-2 rounded-full bg-muted overflow-hidden">
            <div
              className={cn('h-full rounded-full transition-all duration-700', s.probBar)}
              style={{ width: `${Math.min(combinedPct, 100)}%` }}
            />
          </div>
        </div>

        {/* Return + actions row */}
        <div className="flex items-center justify-between gap-2 flex-wrap">
          <p className="text-xs text-muted-foreground">
            Return: <span className={cn('font-semibold', s.text)}>${ticket.potential_return_per_unit}</span>
            <span className="text-muted-foreground/60"> per $1 staked</span>
          </p>

          <div className="flex items-center gap-1.5">
            {/* Copy */}
            <button
              onClick={handleCopy}
              title="Copy ticket"
              className={cn(
                'flex items-center gap-1 text-xs px-2.5 py-1.5 rounded-lg border transition-all duration-150',
                copied
                  ? 'border-emerald-500/50 bg-emerald-500/10 text-emerald-400'
                  : 'border-border/60 hover:border-border bg-muted/30 hover:bg-muted/60 text-muted-foreground hover:text-foreground'
              )}
            >
              {copied
                ? <><ClipboardCheck className="h-3 w-3" /> Copied!</>
                : <><Clipboard className="h-3 w-3" /> Copy</>
              }
            </button>

            {/* Save */}
            {onSave && (
              <button
                onClick={() => onSave(ticket.id)}
                title={isSaved ? 'Unsave ticket' : 'Save ticket'}
                className={cn(
                  'flex items-center gap-1 text-xs px-2.5 py-1.5 rounded-lg border transition-all duration-150',
                  isSaved
                    ? cn('border-opacity-50 text-opacity-100', s.badgeBg, 'border-current')
                    : 'border-border/60 hover:border-border bg-muted/30 hover:bg-muted/60 text-muted-foreground hover:text-foreground'
                )}
              >
                {isSaved
                  ? <><BookmarkCheck className="h-3 w-3" /> Saved</>
                  : <><Bookmark className="h-3 w-3" /> Save</>
                }
              </button>
            )}

            {/* Share */}
            <button
              onClick={handleShare}
              title="Share ticket"
              className="flex items-center gap-1 text-xs px-2.5 py-1.5 rounded-lg border border-border/60 hover:border-border bg-muted/30 hover:bg-muted/60 text-muted-foreground hover:text-foreground transition-all duration-150"
            >
              <Share2 className="h-3 w-3" /> Share
            </button>
          </div>
        </div>

        <p className="text-[10px] text-muted-foreground/50">Generated at {generatedTime}</p>
      </div>
    </div>
  );
}
