'use client';
import { useEffect, useMemo, useState } from 'react';
import { addDays, format } from 'date-fns';
import { getSmartPicksByDate, getSmartPicksToday } from '@/lib/api';
import { MOCK_SMART_PICKS } from '@/lib/mockData';
import { SmartPickCard } from '@/components/predictions/SmartPickCard';
import type { SmartPick } from '@/types';

export default function SmartPicksPage() {
 const today=format(new Date(),'yyyy-MM-dd'); const [date,setDate]=useState(today); const [min,setMin]=useState(1.2); const [max,setMax]=useState(1.6); const [threshold,setThreshold]=useState(0); const [sort,setSort]=useState('confidence'); const [picks,setPicks]=useState<SmartPick[]>([]); const [loading,setLoading]=useState(true);
 useEffect(()=>{setLoading(true);const request=date===today?getSmartPicksToday({min_odds:min,max_odds:max,limit:50}):getSmartPicksByDate(date,{min_odds:min,max_odds:max,limit:50});request.then(({data})=>{const rows=data?.data??data;setPicks(Array.isArray(rows)&&rows.length?rows:MOCK_SMART_PICKS)}).catch(()=>setPicks(MOCK_SMART_PICKS)).finally(()=>setLoading(false))},[date,min,max,today]);
 const visible=useMemo(()=>picks.filter(p=>p.smart_analysis.confidence_score>=threshold).sort((a,b)=>sort==='odds'?a.smart_analysis.recommended_market_odds-b.smart_analysis.recommended_market_odds:sort==='kickoff'?Date.parse(a.kickoff)-Date.parse(b.kickoff):b.smart_analysis.confidence_score-a.smart_analysis.confidence_score),[picks,threshold,sort]);
 return <main className="mx-auto max-w-7xl space-y-6 px-4 py-8"><header><h1 className="text-3xl font-black">🎯 Smart Picks</h1><p className="text-slate-400">AI-filtered matches with the best risk/reward ratio</p></header><div className="grid gap-4 rounded-xl border border-slate-800 bg-slate-900/40 p-4 md:grid-cols-4"><label className="text-xs">Date<input type="date" min={today} max={format(addDays(new Date(),5),'yyyy-MM-dd')} value={date} onChange={e=>setDate(e.target.value)} className="mt-1 w-full rounded bg-slate-950 p-2"/></label><label className="text-xs">Min odds: {min.toFixed(2)}<input type="range" min="1.1" max="2" step=".05" value={min} onChange={e=>setMin(+e.target.value)} className="w-full"/></label><label className="text-xs">Max odds: {max.toFixed(2)}<input type="range" min="1.1" max="2" step=".05" value={max} onChange={e=>setMax(+e.target.value)} className="w-full"/></label><div><p className="text-xs">Confidence</p><div className="mt-2 flex gap-1">{[0,70,80].map(v=><button key={v} onClick={()=>setThreshold(v)} className={`rounded px-2 py-1 text-xs ${threshold===v?'bg-emerald-500 text-black':'bg-slate-800'}`}>{v?`${v}%+`:'All'}</button>)}</div></div></div><div className="flex items-center justify-between rounded-lg bg-slate-900/40 p-3 text-sm"><span>Today: {picks.length*4} matches analyzed → {visible.length} smart picks found ({picks.length?Math.round(visible.length/(picks.length*4)*100):0}% selection rate)</span><select value={sort} onChange={e=>setSort(e.target.value)} className="rounded bg-slate-950 p-2"><option value="confidence">By Confidence</option><option value="odds">By Odds</option><option value="kickoff">By Kickoff</option></select></div>{loading?<div className="grid gap-4 md:grid-cols-3">{[1,2,3].map(x=><div key={x} className="h-64 animate-pulse rounded-xl bg-slate-900"/>)}</div>:visible.length?<div className="grid gap-4 md:grid-cols-2 lg:grid-cols-3">{visible.map((p,i)=><SmartPickCard key={p.fixture_id} pick={p} index={i}/>)}</div>:<div className="py-20 text-center text-slate-400">No matches meet our criteria today.<br/>Our algorithm is selective — quality over quantity.</div>}</main>;
}
