/**
 * Tests for billingController.
 *
 * The webhook signature verification runs against the REAL Stripe SDK's
 * `constructEvent` (not mocked) using a real HMAC signature generated by
 * `Stripe.webhooks.generateTestHeaderString` — both are pure local crypto, no
 * network call — so these tests exercise the actual verification code path,
 * not an assumption about how it behaves. Everything that would need a live
 * API call (creating a Stripe customer/session, retrieving a subscription) is
 * stubbed on a real Stripe client instance.
 *
 * Database access goes through subscriptionModel/userModel, which are mocked
 * here rather than the raw pool — the model layer's own SQL is covered by
 * inspection (upsertSubscription's ON CONFLICT, claimWebhookEvent's atomic
 * claim) rather than re-tested against a fake pool for every controller case.
 */

const Stripe = require('stripe');

const mockStripeClient = new Stripe('sk_test_fake_key_local_hmac_only');
mockStripeClient.customers.create = jest.fn();
mockStripeClient.checkout.sessions.create = jest.fn();
mockStripeClient.billingPortal.sessions.create = jest.fn();
mockStripeClient.subscriptions.retrieve = jest.fn();

const WEBHOOK_SECRET = 'whsec_test_secret';
const PRICE_ID = 'price_test_vip_monthly';

// billingController destructures these at its own require-time
// (`const { getStripeClient } = require('../config/stripe')`), so a later
// test-time reassignment of the module's export property would not affect
// the reference billingController already holds. Wrapping in jest.fn() keeps
// the same function identity while still letting a single test override its
// behavior via mockImplementationOnce.
jest.mock('../src/config/stripe', () => ({
  getStripeClient: jest.fn(() => mockStripeClient),
  getPriceId: () => 'price_test_vip_monthly',
  getWebhookSecret: () => 'whsec_test_secret',
}));

jest.mock('../src/config/database', () => ({
  pool: { connect: jest.fn() },
}));

jest.mock('../src/models/subscriptionModel');
jest.mock('../src/models/userModel');

const { pool } = require('../src/config/database');
const subscriptionModel = require('../src/models/subscriptionModel');
const userModel = require('../src/models/userModel');
const billingController = require('../src/controllers/billingController');

function makeRes() {
  return {
    statusCode: 200,
    body: undefined,
    status(code) { this.statusCode = code; return this; },
    json(body) { this.body = body; return this; },
    sendStatus(code) { this.statusCode = code; this.body = undefined; return this; },
  };
}

function signedRequest(payload) {
  const raw = Buffer.from(JSON.stringify(payload));
  const header = Stripe.webhooks.generateTestHeaderString({ payload: raw, secret: WEBHOOK_SECRET });
  return { headers: { 'stripe-signature': header }, body: raw };
}

/** Fake transactional client: BEGIN/COMMIT/ROLLBACK tracked, everything else a no-op. */
function makeTxClient() {
  return {
    calls: [],
    query(sql) { this.calls.push(sql); return { rows: [] }; },
    release: jest.fn(),
  };
}

beforeEach(() => {
  jest.clearAllMocks();
});

// ── createCheckoutSession ─────────────────────────────────────────────────────

describe('createCheckoutSession', () => {
  test('creates a Stripe customer on first checkout and persists the id', async () => {
    userModel.findById.mockResolvedValue({ id: 7, email: 'a@example.com' });
    subscriptionModel.getStripeCustomerId.mockResolvedValue(null);
    mockStripeClient.customers.create.mockResolvedValue({ id: 'cus_new' });
    mockStripeClient.checkout.sessions.create.mockResolvedValue({ url: 'https://checkout.stripe.com/session/abc' });

    const req = { user: { id: 7 } };
    const res = makeRes();
    await billingController.createCheckoutSession(req, res);

    expect(mockStripeClient.customers.create).toHaveBeenCalledWith(
      expect.objectContaining({ email: 'a@example.com', metadata: { userId: '7' } })
    );
    expect(subscriptionModel.setStripeCustomerId).toHaveBeenCalledWith(7, 'cus_new');
    expect(res.statusCode).toBe(200);
    expect(res.body).toEqual({ url: 'https://checkout.stripe.com/session/abc' });
  });

  test('reuses an existing Stripe customer instead of creating a duplicate', async () => {
    userModel.findById.mockResolvedValue({ id: 7, email: 'a@example.com' });
    subscriptionModel.getStripeCustomerId.mockResolvedValue('cus_existing');
    mockStripeClient.checkout.sessions.create.mockResolvedValue({ url: 'https://checkout.stripe.com/session/xyz' });

    await billingController.createCheckoutSession({ user: { id: 7 } }, makeRes());

    expect(mockStripeClient.customers.create).not.toHaveBeenCalled();
    expect(mockStripeClient.checkout.sessions.create).toHaveBeenCalledWith(
      expect.objectContaining({ customer: 'cus_existing' })
    );
  });

  test('always charges the server-configured price — never one supplied by the client', async () => {
    userModel.findById.mockResolvedValue({ id: 7, email: 'a@example.com' });
    subscriptionModel.getStripeCustomerId.mockResolvedValue('cus_existing');
    mockStripeClient.checkout.sessions.create.mockResolvedValue({ url: 'https://checkout.stripe.com/x' });

    // Even if a caller's body tried to smuggle a price, createCheckoutSession
    // never reads req.body for one — there is nothing to smuggle it through.
    const req = { user: { id: 7 }, body: { priceId: 'price_attacker_supplied' } };
    await billingController.createCheckoutSession(req, makeRes());

    expect(mockStripeClient.checkout.sessions.create).toHaveBeenCalledWith(
      expect.objectContaining({ line_items: [{ price: PRICE_ID, quantity: 1 }] })
    );
  });

  test('returns 503 rather than crashing when Stripe is not configured', async () => {
    const stripeConfig = require('../src/config/stripe');
    stripeConfig.getStripeClient.mockImplementationOnce(() => {
      throw new Error('STRIPE_SECRET_KEY is not configured');
    });

    const res = makeRes();
    await billingController.createCheckoutSession({ user: { id: 7 } }, res);

    expect(res.statusCode).toBe(503);
  });
});

// ── createPortalSession ────────────────────────────────────────────────────────

describe('createPortalSession', () => {
  test('opens a portal session for an existing billing customer', async () => {
    subscriptionModel.getStripeCustomerId.mockResolvedValue('cus_existing');
    mockStripeClient.billingPortal.sessions.create.mockResolvedValue({ url: 'https://billing.stripe.com/p/abc' });

    const res = makeRes();
    await billingController.createPortalSession({ user: { id: 7 } }, res);

    expect(mockStripeClient.billingPortal.sessions.create).toHaveBeenCalledWith(
      expect.objectContaining({ customer: 'cus_existing' })
    );
    expect(res.body).toEqual({ url: 'https://billing.stripe.com/p/abc' });
  });

  test('404s a user who has never started a subscription — nothing to manage', async () => {
    subscriptionModel.getStripeCustomerId.mockResolvedValue(null);

    const res = makeRes();
    await billingController.createPortalSession({ user: { id: 7 } }, res);

    expect(res.statusCode).toBe(404);
    expect(mockStripeClient.billingPortal.sessions.create).not.toHaveBeenCalled();
  });
});

// ── getStatus ──────────────────────────────────────────────────────────────────

describe('getStatus', () => {
  test('reports free plan with no subscription history', async () => {
    userModel.findById.mockResolvedValue({ id: 7, plan: 'free', trial_ends_at: '2026-09-21T00:00:00.000Z' });
    subscriptionModel.findLatestByUserId.mockResolvedValue(null);

    const res = makeRes();
    await billingController.getStatus({ user: { id: 7 } }, res);

    expect(res.body).toEqual({
      plan: 'free',
      trialEndsAt: '2026-09-21T00:00:00.000Z',
      subscription: null,
    });
  });

  test('response carries no Stripe ids — plan info only, for any client', async () => {
    userModel.findById.mockResolvedValue({ id: 7, plan: 'vip', trial_ends_at: null });
    subscriptionModel.findLatestByUserId.mockResolvedValue({
      status: 'active', current_period_end: '2026-10-14T00:00:00.000Z', cancel_at_period_end: false,
    });

    const res = makeRes();
    await billingController.getStatus({ user: { id: 7 } }, res);

    expect(JSON.stringify(res.body)).not.toMatch(/cus_|sub_/);
    expect(res.body.subscription).toEqual({
      status: 'active', currentPeriodEnd: '2026-10-14T00:00:00.000Z', cancelAtPeriodEnd: false,
    });
  });
});

// ── webhook ────────────────────────────────────────────────────────────────────

describe('webhook', () => {
  test('rejects a request with an invalid signature before touching the database', async () => {
    const req = { headers: { 'stripe-signature': 't=1,v1=deadbeef' }, body: Buffer.from('{}') };
    const res = makeRes();

    await billingController.webhook(req, res);

    expect(res.statusCode).toBe(400);
    expect(pool.connect).not.toHaveBeenCalled();
  });

  test('checkout.session.completed upserts the subscription and sets plan=vip', async () => {
    const client = makeTxClient();
    pool.connect.mockResolvedValue(client);
    subscriptionModel.claimWebhookEvent.mockResolvedValue(true);
    mockStripeClient.subscriptions.retrieve.mockResolvedValue({
      id: 'sub_123', status: 'active', current_period_end: 1_800_000_000, cancel_at_period_end: false,
    });

    const req = signedRequest({
      id: 'evt_1',
      type: 'checkout.session.completed',
      data: { object: {
        mode: 'subscription', customer: 'cus_1', subscription: 'sub_123', metadata: { userId: '7' },
      } },
    });
    const res = makeRes();
    await billingController.webhook(req, res);

    expect(res.statusCode).toBe(200);
    expect(subscriptionModel.upsertSubscription).toHaveBeenCalledWith(client, expect.objectContaining({
      userId: 7, stripeSubscriptionId: 'sub_123', status: 'active',
    }));
    expect(subscriptionModel.setPlan).toHaveBeenCalledWith(client, 7, 'vip');
    expect(client.calls).toContain('COMMIT');
    expect(client.calls).not.toContain('ROLLBACK');
  });

  test('customer.subscription.deleted downgrades the account to free', async () => {
    const client = makeTxClient();
    pool.connect.mockResolvedValue(client);
    subscriptionModel.claimWebhookEvent.mockResolvedValue(true);
    subscriptionModel.findUserIdByStripeSubscriptionId.mockResolvedValue(7);

    const req = signedRequest({
      id: 'evt_2',
      type: 'customer.subscription.deleted',
      data: { object: { id: 'sub_123', customer: 'cus_1', cancel_at_period_end: false } },
    });
    const res = makeRes();
    await billingController.webhook(req, res);

    expect(subscriptionModel.upsertSubscription).toHaveBeenCalledWith(
      client, expect.objectContaining({ status: 'canceled' })
    );
    expect(subscriptionModel.setPlan).toHaveBeenCalledWith(client, 7, 'free');
    expect(res.statusCode).toBe(200);
  });

  test('customer.subscription.updated syncs plan from the new status (past_due recovery)', async () => {
    const client = makeTxClient();
    pool.connect.mockResolvedValue(client);
    subscriptionModel.claimWebhookEvent.mockResolvedValue(true);
    subscriptionModel.findUserIdByStripeSubscriptionId.mockResolvedValue(7);

    const req = signedRequest({
      id: 'evt_3',
      type: 'customer.subscription.updated',
      data: { object: {
        id: 'sub_123', customer: 'cus_1', status: 'active',
        current_period_end: 1_800_000_000, cancel_at_period_end: false,
      } },
    });
    await billingController.webhook(req, makeRes());

    // A subscription that recovered from past_due to active must re-upgrade
    // the account — without this, a customer whose retried payment succeeds
    // stays downgraded until they cancel and resubscribe.
    expect(subscriptionModel.setPlan).toHaveBeenCalledWith(client, 7, 'vip');
  });

  test('invoice.payment_failed marks the subscription past_due without touching users.plan', async () => {
    const client = makeTxClient();
    pool.connect.mockResolvedValue(client);
    subscriptionModel.claimWebhookEvent.mockResolvedValue(true);
    subscriptionModel.findUserIdByStripeSubscriptionId.mockResolvedValue(7);

    const req = signedRequest({
      id: 'evt_4',
      type: 'invoice.payment_failed',
      data: { object: { subscription: 'sub_123', customer: 'cus_1' } },
    });
    await billingController.webhook(req, makeRes());

    expect(subscriptionModel.markPastDue).toHaveBeenCalledWith(client, 'sub_123');
    // Entitlement is untouched here — Stripe gets more retry attempts before
    // the subscription actually cancels.
    expect(subscriptionModel.setPlan).not.toHaveBeenCalled();
  });

  test('a redelivered event is claimed exactly once and skips reprocessing', async () => {
    const client = makeTxClient();
    pool.connect.mockResolvedValue(client);
    subscriptionModel.claimWebhookEvent.mockResolvedValue(false); // already processed

    const req = signedRequest({
      id: 'evt_5',
      type: 'customer.subscription.deleted',
      data: { object: { id: 'sub_123', customer: 'cus_1' } },
    });
    const res = makeRes();
    await billingController.webhook(req, res);

    expect(res.statusCode).toBe(200);
    expect(subscriptionModel.upsertSubscription).not.toHaveBeenCalled();
    expect(subscriptionModel.setPlan).not.toHaveBeenCalled();
  });

  test('an unhandled event type is acknowledged without side effects', async () => {
    const client = makeTxClient();
    pool.connect.mockResolvedValue(client);
    subscriptionModel.claimWebhookEvent.mockResolvedValue(true);

    const req = signedRequest({ id: 'evt_6', type: 'customer.updated', data: { object: {} } });
    const res = makeRes();
    await billingController.webhook(req, res);

    expect(res.statusCode).toBe(200);
    expect(subscriptionModel.upsertSubscription).not.toHaveBeenCalled();
    expect(client.calls).toContain('COMMIT');
  });

  test('a processing failure rolls back so Stripe\'s retry is reprocessed, not skipped', async () => {
    const client = makeTxClient();
    pool.connect.mockResolvedValue(client);
    subscriptionModel.claimWebhookEvent.mockResolvedValue(true);
    subscriptionModel.findUserIdByStripeSubscriptionId.mockRejectedValue(new Error('connection reset'));

    const req = signedRequest({
      id: 'evt_7',
      type: 'customer.subscription.deleted',
      data: { object: { id: 'sub_123', customer: 'cus_1' } },
    });
    const res = makeRes();
    await billingController.webhook(req, res);

    expect(res.statusCode).toBe(500);
    expect(client.calls).toContain('ROLLBACK');
    expect(client.calls).not.toContain('COMMIT');
  });
});
