import { create } from 'zustand';
import { ticketApi } from '@/lib/api';
import { logger, userMessage } from '@/lib/logger';
import type { Ticket, TicketTierKey } from '@/types';

// ── Helpers ───────────────────────────────────────────────────────────────────

function formatTicketText(ticket: Ticket): string {
  const lines = [
    `🎰 ${ticket.emoji} ${ticket.name} Ticket`,
    `Combined Odds: ${ticket.combined_odds}x`,
    ``,
    ...ticket.legs.map(
      (leg, i) =>
        `${i + 1}. ${leg.match}\n   ${leg.selection} @ ${leg.odds}\n   (${Math.round(leg.probability * 100)}% probability)`
    ),
    ``,
    `Potential Return: $${ticket.potential_return_per_unit} per $1 staked`,
    `Generated by BetAction AI`,
  ];
  return lines.join('\n');
}

// ── State shape ───────────────────────────────────────────────────────────────

interface TicketState {
  tickets:       Ticket[];
  selectedTier:  TicketTierKey | 'all';
  isLoading:     boolean;
  error:         string | null;
  savedTicketIds: string[];
  /** Plan the server applied to this response. */
  plan:          'free' | 'vip';
  /** True when tiers or legs were withheld because of that plan. */
  limited:       boolean;

  fetchTodayTickets: ()                        => Promise<void>;
  filterByTier:      (tier: TicketTierKey | 'all') => void;
  saveTicket:        (ticketId: string)        => void;
  unsaveTicket:      (ticketId: string)        => void;
  copyTicketToClipboard: (ticket: Ticket)      => Promise<boolean>;
  clearError:        ()                        => void;
  reset:             ()                        => void;
}

// ── Store ─────────────────────────────────────────────────────────────────────

const INITIAL_STATE = {
  tickets:        [] as Ticket[],
  selectedTier:   'all' as TicketTierKey | 'all',
  isLoading:      false,
  error:          null as string | null,
  savedTicketIds: [] as string[],
  plan:           'free' as 'free' | 'vip',
  limited:        false,
};

export const useTicketStore = create<TicketState>()((set, get) => ({
  ...INITIAL_STATE,

  // ── Fetch today's tickets ─────────────────────────────────────────────────

  fetchTodayTickets: async () => {
    set({ isLoading: true, error: null });
    try {
      const { data } = await ticketApi.today();
      const tickets: Ticket[] = Array.isArray(data?.data) ? data.data : [];
      // An empty list is a legitimate answer: on a thin fixture day the backend
      // offers fewer tiers, or none. It used to be replaced with mock tickets —
      // fabricated bets a customer could not win.
      set({
        tickets,
        plan: data?.plan ?? 'free',
        limited: Boolean(data?.limited),
        error: null,
      });
    } catch (err) {
      logger.error('Failed to load tickets', err);
      set({
        tickets: [],
        error: userMessage(err, "We couldn't load today's tickets. Please try again shortly."),
      });
    } finally {
      set({ isLoading: false });
    }
  },

  // ── Tier filter ───────────────────────────────────────────────────────────

  filterByTier: (tier) => set({ selectedTier: tier }),

  // ── Save / unsave ─────────────────────────────────────────────────────────

  saveTicket: (ticketId) =>
    set((s) => ({
      savedTicketIds: s.savedTicketIds.includes(ticketId)
        ? s.savedTicketIds
        : [...s.savedTicketIds, ticketId],
    })),

  unsaveTicket: (ticketId) =>
    set((s) => ({
      savedTicketIds: s.savedTicketIds.filter((id) => id !== ticketId),
    })),

  // ── Copy to clipboard ─────────────────────────────────────────────────────

  copyTicketToClipboard: async (ticket) => {
    try {
      await navigator.clipboard.writeText(formatTicketText(ticket));
      return true;
    } catch {
      return false;
    }
  },

  clearError: () => set({ error: null }),

  /** Called on logout — see stores/resetStores.ts. */
  reset: () => set({ ...INITIAL_STATE }),
}));
