import { create } from 'zustand';
import { ticketApi } from '@/lib/api';
import { MOCK_TICKETS } from '@/lib/mockData';
import type { Ticket, TicketTierKey } from '@/types';

// ── Helpers ───────────────────────────────────────────────────────────────────

function formatTicketText(ticket: Ticket): string {
  const lines = [
    `🎰 ${ticket.emoji} ${ticket.name} Ticket`,
    `Combined Odds: ${ticket.combined_odds}x`,
    ``,
    ...ticket.legs.map(
      (leg, i) =>
        `${i + 1}. ${leg.match}\n   ${leg.selection} @ ${leg.odds}\n   (${Math.round(leg.probability * 100)}% probability)`
    ),
    ``,
    `Potential Return: $${ticket.potential_return_per_unit} per $1 staked`,
    `Generated by BetAction AI`,
  ];
  return lines.join('\n');
}

// ── State shape ───────────────────────────────────────────────────────────────

interface TicketState {
  tickets:       Ticket[];
  selectedTier:  TicketTierKey | 'all';
  isLoading:     boolean;
  error:         string | null;
  savedTicketIds: string[];

  fetchTodayTickets: ()                        => Promise<void>;
  filterByTier:      (tier: TicketTierKey | 'all') => void;
  saveTicket:        (ticketId: string)        => void;
  unsaveTicket:      (ticketId: string)        => void;
  copyTicketToClipboard: (ticket: Ticket)      => Promise<boolean>;
  clearError:        ()                        => void;
}

// ── Store ─────────────────────────────────────────────────────────────────────

export const useTicketStore = create<TicketState>()((set, get) => ({
  tickets:        [],
  selectedTier:   'all',
  isLoading:      false,
  error:          null,
  savedTicketIds: [],

  // ── Fetch today's tickets ─────────────────────────────────────────────────

  fetchTodayTickets: async () => {
    set({ isLoading: true, error: null });
    try {
      const { data } = await ticketApi.today();
      const tickets: Ticket[] = Array.isArray(data?.data) ? data.data : [];
      set({ tickets: tickets.length > 0 ? tickets : MOCK_TICKETS });
    } catch {
      // Network error or API unavailable — fall back to mock data
      set({ tickets: MOCK_TICKETS });
    } finally {
      set({ isLoading: false });
    }
  },

  // ── Tier filter ───────────────────────────────────────────────────────────

  filterByTier: (tier) => set({ selectedTier: tier }),

  // ── Save / unsave ─────────────────────────────────────────────────────────

  saveTicket: (ticketId) =>
    set((s) => ({
      savedTicketIds: s.savedTicketIds.includes(ticketId)
        ? s.savedTicketIds
        : [...s.savedTicketIds, ticketId],
    })),

  unsaveTicket: (ticketId) =>
    set((s) => ({
      savedTicketIds: s.savedTicketIds.filter((id) => id !== ticketId),
    })),

  // ── Copy to clipboard ─────────────────────────────────────────────────────

  copyTicketToClipboard: async (ticket) => {
    try {
      await navigator.clipboard.writeText(formatTicketText(ticket));
      return true;
    } catch {
      return false;
    }
  },

  clearError: () => set({ error: null }),
}));
